#!/usr/bin/env python3
"""Generate third_party/tok_unicode_ps.h - Unicode P (punctuation), S (symbol)
and M (mark) category tables for the DeepSeek pre-tokenizer.

The released tokenizer.json splits on \\p{P} and \\p{S} and matches letter runs
as [\\p{L}\\p{M}]; this header provides the ranges as compact sorted intervals.
Run:  python3 tools/gen_unicode_ps.py > third_party/tok_unicode_ps.h
"""
import sys
import unicodedata


def ranges(cats):
    lo = hi = None
    for cp in range(0x110000):
        ch = chr(cp)
        try:
            cat = unicodedata.category(ch)
        except ValueError:  # surrogate
            continue
        if cat and cat[0] in cats:
            if lo is None:
                lo = hi = cp
            elif cp == hi + 1:
                hi = cp
            else:
                yield lo, hi
                lo = hi = cp
    if lo is not None:
        yield lo, hi


def emit(name, it):
    rs = list(it)
    sys.stdout.write(f"static const uint32_t {name}[][2] = {{\n")
    for i in range(0, len(rs), 6):
        row = ", ".join(f"{{0x{a:X},0x{b:X}}}" for a, b in rs[i:i + 6])
        sys.stdout.write(f"    {row},\n")
    sys.stdout.write("};\n")
    sys.stdout.write(f"static const int {name}_n = {len(rs)};\n\n")
    return rs


print("/* GENERATED by tools/gen_unicode_ps.py, do not edit by hand. */")
print("#ifndef TOK_UNICODE_PS_H")
print("#define TOK_UNICODE_PS_H")
print("#include <stdint.h>")
print()
ps = emit("uni_PS", ranges("PS"))
m = emit("uni_M", ranges("M"))
print("static inline int is_PS(uint32_t c){ return uni_in(uni_PS,uni_PS_n,c); }")
print("static inline int is_M(uint32_t c){ return uni_in(uni_M,uni_M_n,c); }")
print("static inline int is_LM(uint32_t c){ return is_L(c)||is_M(c); }")
print("#endif")
