/* SPDX-License-Identifier: Apache-2.0 */
#define _POSIX_C_SOURCE 200809L
/* test_dsv4_model.c - tiny-model graph test.
 *
 * Runs 130 forward positions on the synthetic 4-layer checkpoint and compares
 * every position's logits against tools/reference_tiny_dsv4.py (an independent
 * scalar oracle), crossing the ratio-4 and ratio-128 compression boundaries.
 * The oracle JSON is generated by
 * tools/reference_tiny_dsv4.py into tests/fixtures/tiny_dsv4/ref_logits.json.
 *
 * Eight expert cache slots and two OpenMP threads exercise mixed hit/miss
 * batches, including the rule that hit slots stay pinned during prefetch.
 */
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "dsv4.h"
#include "dsv4_internal.h"
#include "json.h"

static int fails = 0;
#define CHECK(cond, msg) do { if (!(cond)) { printf("FAIL: %s\n", msg); fails++; } } while (0)

static double ref_at(jval *root, const char *pos, int v)
{
    jval *arr = json_get(root, pos);
    if (!arr || arr->t != J_ARR || v >= arr->len) return NAN;
    return arr->kids[v]->num;
}

static int same_context(const DSV4Model *a, const DSV4Model *b)
{
    if (memcmp(a->state, b->state,
               (size_t)a->cfg.hc_mult * a->cfg.hidden * sizeof(float)) != 0) {
        printf("context mismatch: model state\n");
        return 0;
    }
    for (int L = 0; L < a->cfg.n_layers; L++) {
        const DSV4LayerRun *ar = &a->run[L], *br = &b->run[L];
        const int ratio = a->cfg.compress_ratio[L];
        const int coff = ratio == 4 ? 2 : 1;
        if (ar->comp_count != br->comp_count || ar->idx_count != br->idx_count) {
            printf("context mismatch: layer %d counts comp %d/%d idx %d/%d\n",
                   L, ar->comp_count, br->comp_count,
                   ar->idx_count, br->idx_count);
            return 0;
        }
        if (memcmp(ar->kv_cache, br->kv_cache,
                   (size_t)ar->kv_cap * a->cfg.head_dim * sizeof(float)) != 0) {
            printf("context mismatch: layer %d kv cache\n", L);
            return 0;
        }
        if (ratio) {
            size_t n = (size_t)coff * ratio * coff * a->cfg.head_dim;
            if (memcmp(ar->kv_state, br->kv_state, n * sizeof(float)) != 0 ||
                memcmp(ar->score_state, br->score_state, n * sizeof(float)) != 0) {
                printf("context mismatch: layer %d compressor state\n", L);
                return 0;
            }
        }
        if (ratio == 4) {
            size_t n = (size_t)coff * ratio * coff * a->cfg.index_dim;
            size_t rows = (size_t)(ar->kv_cap - a->cfg.window) * a->cfg.index_dim;
            if (memcmp(ar->idx_kv_state, br->idx_kv_state,
                       n * sizeof(float)) != 0 ||
                memcmp(ar->idx_score_state, br->idx_score_state,
                       n * sizeof(float)) != 0) {
                printf("context mismatch: layer %d indexer state\n", L);
                return 0;
            }
            if (memcmp(ar->idx_cache, br->idx_cache,
                       rows * sizeof(float)) != 0) {
                printf("context mismatch: layer %d indexer cache\n", L);
                return 0;
            }
        }
    }
    return 1;
}

int main(int argc, char **argv)
{
    const char *fdir = argc > 1 ? argv[1] : "tests/fixtures/tiny_dsv4";
    char path[4096];

    snprintf(path, sizeof path, "%s/config.json", fdir);
    DSV4Config cfg;
    if (!dsv4_config_load_file(&cfg, path)) { printf("FAIL: config load\n"); return 1; }

    DSV4Options opt;
    memset(&opt, 0, sizeof opt);
    opt.max_context = 132;
    opt.threads = 2;
    /* Eight slots produce mixed hit/miss batches across the four layers. */
    opt.expert_cache_bytes = 8u * (13369344ull + 4 * 4096ull);
    opt.wo_a_cache_layers = cfg.n_layers;

    CHECK(unsetenv("DSV4_NO_EXPERT_OVERLAP") == 0,
          "enable expert overlap for default-path test");
    CHECK(unsetenv("DSV4_NO_LAYER_OVERLAP") == 0,
          "enable layer overlap for default-path test");
    CHECK(setenv("DSV4_EXPERT_CACHE_GLOBAL", "1", 1) == 0,
          "select global expert cache for counter oracle");

    DSV4Model *m = dsv4_model_open(fdir, &opt);
    if (!m) { printf("FAIL: model open\n"); return 1; }
    CHECK(dsv4_dspark_ready(m) == 0,
          "tiny checkpoint without DSpark fields keeps draft disabled");

    /* reference logits */
    snprintf(path, sizeof path, "%s/ref_logits.json", fdir);
    FILE *f = fopen(path, "rb");
    if (!f) { printf("FAIL: no ref_logits.json; run tools/reference_tiny_dsv4.py first\n"); return 1; }
    if (fseek(f, 0, SEEK_END) != 0) return 1;
    long n = ftell(f);
    fseek(f, 0, SEEK_SET);
    char *txt = (char *)malloc((size_t)n + 1);
    size_t gotn = fread(txt, 1, (size_t)n, f);
    (void)gotn;
    fclose(f);
    txt[n] = 0;
    char *arena = NULL;
    jval *ref = json_parse(txt, &arena);
    if (!ref) { printf("FAIL: ref_logits.json parse\n"); return 1; }

    /* fixed deterministic token sequence */
    static const int seq[16] = { 3, 7, 1, 14, 5, 9, 2, 11, 0, 13, 6, 4, 12, 8, 15, 10 };
    float *logits = (float *)malloc((size_t)cfg.vocab * sizeof(float));
    double maxdiff = 0.0; int maxpos = 0, maxv = 0;
    for (int pos = 0; pos < 130; pos++) {
        int tok = seq[pos % 16];
        if (dsv4_forward_token(m, tok, pos, logits) != 0) {
            printf("FAIL: forward at pos %d\n", pos);
            return 1;
        }
        char key[16];
        snprintf(key, sizeof key, "%d", pos);
        for (int v = 0; v < cfg.vocab; v++) {
            double refv = ref_at(ref, key, v);
            double d = fabs((double)logits[v] - refv);
            if (d > maxdiff) { maxdiff = d; maxpos = pos; maxv = v; }
            if (d != 0.0) {
                printf("FAIL: logits[%d] at pos %d: C %.6f ref %.6f\n", v, pos,
                       logits[v], refv);
                fails++;
                if (fails > 20) { dsv4_model_close(m); return 1; }
            }
        }
    }
    /* The eight-slot schedule deterministically mixes 874 hits with 166 misses.
     * Each tiny expert is 64 raw bytes (16 scale + 48 weight). */
    printf("counters: hits=%ld misses=%ld coalesced=%ld batch=%ld bytes=%llu\n",
           m->cache_hits, m->cache_misses, m->coalesced_loads, m->batch_prefetched,
           (unsigned long long)m->expert_bytes_read);
    CHECK(m->cache_hits == 874, "874 expert hits");
    CHECK(m->cache_misses == 166, "166 expert misses");
    CHECK(m->coalesced_loads == 166, "166 coalesced loads");
    CHECK(m->batch_prefetched == 166, "166 batch-prefetched");
    CHECK(m->expert_bytes_read == 166ull * 64ull, "expert bytes read");
    CHECK(m->wo_a_cache_misses == 4, "four initial wo_a cache fills");
    CHECK(m->wo_a_cache_hits == 516, "516 wo_a cache hits");

    /* The background next-layer loader is scheduling-only. Exercise the same
     * token-major recurrence with its synchronous fallback in this binary. */
    CHECK(setenv("DSV4_NO_LAYER_OVERLAP", "1", 1) == 0,
          "disable layer overlap for A/B test");
    CHECK(setenv("DSV4_EXPERT_IO_WORKERS", "1", 1) == 0,
          "select one persistent expert I/O worker");
    CHECK(unsetenv("DSV4_EXPERT_CACHE_GLOBAL") == 0,
          "select default per-layer expert cache");
    DSV4Model *layer_sync_m = dsv4_model_open(fdir, &opt);
    float *layer_sync_logits = (float *)malloc((size_t)cfg.vocab * sizeof(float));
    CHECK(layer_sync_m != NULL, "synchronous layer model open");
    CHECK(layer_sync_logits != NULL, "synchronous layer logits allocation");
    if (layer_sync_m && layer_sync_logits) {
        CHECK(layer_sync_m->cache_per_layer == 1,
              "per-layer expert cache enabled");
        for (int pos = 0; pos < 130; pos++)
            CHECK(dsv4_forward_token(layer_sync_m, seq[pos % 16], pos,
                                     layer_sync_logits) == 0,
                  "synchronous layer forward");
        for (int v = 0; v < cfg.vocab; v++)
            CHECK(layer_sync_logits[v] == logits[v],
                  "overlapped and synchronous layer logits match");
    }
    dsv4_model_close(layer_sync_m);
    free(layer_sync_logits);
    CHECK(unsetenv("DSV4_NO_LAYER_OVERLAP") == 0,
          "restore layer overlap after A/B test");
    CHECK(unsetenv("DSV4_EXPERT_IO_WORKERS") == 0,
          "restore automatic expert I/O workers");

    /* Layer-major prefill must preserve the final scalar result even across
     * both compressor boundaries. It intentionally has different cache I/O
     * counters because each layer bundle is loaded only once. */
    DSV4Model *batch_m = dsv4_model_open(fdir, &opt);
    float *batch_logits = (float *)malloc((size_t)cfg.vocab * sizeof(float));
    int batch_ids[130];
    CHECK(batch_m != NULL, "batch model open");
    CHECK(batch_logits != NULL, "batch logits allocation");
    for (int pos = 0; pos < 130; pos++) batch_ids[pos] = seq[pos % 16];
    if (batch_m && batch_logits) {
        CHECK(dsv4_prefill(batch_m, batch_ids, 130, 0, batch_logits) == 0,
              "layer-major prefill");
        for (int v = 0; v < cfg.vocab; v++) {
            double refv = ref_at(ref, "129", v);
            CHECK((double)batch_logits[v] == refv, "batch logits match scalar oracle");
            CHECK(batch_logits[v] == logits[v], "batch logits match token-major path");
        }
        CHECK(batch_m->forward_steps == 130, "batch forward-step accounting");
    }
    dsv4_model_close(batch_m);
    free(batch_logits);

    /* Speculative verification needs every batch position's logits, while
     * DSpark conditions on the mean across the completed HC lanes at selected
     * target layers. The batched head must retain the scalar oracle exactly,
     * and target captures must be independent of prefill segmentation. */
    static const int capture_layers[2] = { 1, 3 };
    const size_t all_logits_n = (size_t)130 * cfg.vocab;
    const size_t captures_n = (size_t)130 * 2 * cfg.hidden;
    DSV4Model *capture_m = dsv4_model_open(fdir, &opt);
    float *all_logits = (float *)malloc(all_logits_n * sizeof(float));
    float *captures = (float *)malloc(captures_n * sizeof(float));
    CHECK(capture_m != NULL, "capture model open");
    CHECK(all_logits != NULL, "all-position logits allocation");
    CHECK(captures != NULL, "target-hidden capture allocation");
    if (capture_m && all_logits && captures) {
        CHECK(dsv4_prefill_capture(capture_m, batch_ids, 130, 0, NULL,
                                    all_logits, capture_layers, 2, captures) == 0,
              "all-position logits and target-layer capture");
        for (int pos = 0; pos < 130; pos++) {
            char key[16];
            snprintf(key, sizeof key, "%d", pos);
            for (int v = 0; v < cfg.vocab; v++)
                CHECK((double)all_logits[(size_t)pos * cfg.vocab + v] ==
                          ref_at(ref, key, v),
                      "batched head matches every scalar-oracle position");
        }
        CHECK(capture_m->forward_steps == 130,
              "capture forward-step accounting");
    }

    DSV4Model *capture_split_m = dsv4_model_open(fdir, &opt);
    float *split_captures = (float *)malloc(captures_n * sizeof(float));
    float *capture_last_logits = (float *)malloc((size_t)cfg.vocab * sizeof(float));
    CHECK(capture_split_m != NULL, "split capture model open");
    CHECK(split_captures != NULL, "split target-hidden capture allocation");
    CHECK(capture_last_logits != NULL, "split capture logits allocation");
    if (capture_m && captures && capture_split_m && split_captures &&
        capture_last_logits) {
        CHECK(dsv4_prefill_capture(capture_split_m, batch_ids, 57, 0,
                                    capture_last_logits, NULL, capture_layers, 2,
                                    split_captures) == 0,
              "first segmented target-layer capture");
        CHECK(dsv4_prefill_capture(
                  capture_split_m, batch_ids + 57, 73, 57, capture_last_logits,
                  NULL, capture_layers, 2,
                  split_captures + (size_t)57 * 2 * cfg.hidden) == 0,
              "second segmented target-layer capture");
        for (size_t i = 0; i < captures_n; i++)
            CHECK(split_captures[i] == captures[i],
                  "segmented target-layer captures match one-shot capture");
        for (int v = 0; v < cfg.vocab; v++)
            CHECK(capture_last_logits[v] == logits[v],
                  "capture path final logits match scalar path");
    }
    dsv4_model_close(capture_split_m);
    dsv4_model_close(capture_m);
    free(capture_last_logits);
    free(split_captures);
    free(captures);
    free(all_logits);

    /* A rejected speculative suffix must leave no positional state behind.
     * Start close enough to the 128-token ring boundary that the wrong suffix
     * overwrites historical slots, then restore and replay two accepted rows. */
    int rollback_ids[132];
    for (int pos = 0; pos < 132; pos++) rollback_ids[pos] = seq[pos % 16];
    int wrong_ids[6];
    wrong_ids[0] = rollback_ids[126];
    wrong_ids[1] = rollback_ids[127];
    for (int i = 2; i < 6; i++)
        wrong_ids[i] = (rollback_ids[126 + i] + 5) % cfg.vocab;
    DSV4Model *expected_m = dsv4_model_open(fdir, &opt);
    DSV4Model *rollback_m = dsv4_model_open(fdir, &opt);
    float *expected_logits = (float *)malloc((size_t)cfg.vocab * sizeof(float));
    float *rollback_logits = (float *)malloc((size_t)cfg.vocab * sizeof(float));
    DSV4ContextSnapshot *snap = dsv4_context_snapshot_create(rollback_m, 6);
    CHECK(expected_m != NULL, "rollback reference model open");
    CHECK(rollback_m != NULL, "rollback model open");
    CHECK(expected_logits != NULL && rollback_logits != NULL,
          "rollback logits allocations");
    CHECK(snap != NULL, "bounded context snapshot allocation");
    if (expected_m && rollback_m && expected_logits && rollback_logits && snap) {
        CHECK(dsv4_prefill(expected_m, rollback_ids, 126, 0,
                           expected_logits) == 0,
              "rollback reference prefix");
        CHECK(dsv4_prefill(rollback_m, rollback_ids, 126, 0,
                           rollback_logits) == 0,
              "rollback test prefix");
        CHECK(same_context(expected_m, rollback_m),
              "rollback models agree before speculative transaction");
        CHECK(dsv4_context_snapshot_take(snap, 126, 6) == 0,
              "take bounded context snapshot");
        CHECK(dsv4_prefill(rollback_m, wrong_ids, 6, 126,
                           rollback_logits) == 0,
              "consume speculative block with rejected suffix");
        CHECK(dsv4_context_snapshot_restore(snap) == 0,
              "restore bounded context snapshot");
        CHECK(dsv4_prefill(expected_m, rollback_ids + 126, 2, 126,
                           expected_logits) == 0,
              "reference accepted prefix");
        CHECK(dsv4_prefill(rollback_m, rollback_ids + 126, 2, 126,
                           rollback_logits) == 0,
              "replay accepted prefix after rollback");
        CHECK(same_context(expected_m, rollback_m),
              "rollback and replay restore every runtime-state byte");
        for (int pos = 128; pos < 132; pos++) {
            CHECK(dsv4_forward_token(expected_m, rollback_ids[pos], pos,
                                     expected_logits) == 0,
                  "reference forward after rollback boundary");
            CHECK(dsv4_forward_token(rollback_m, rollback_ids[pos], pos,
                                     rollback_logits) == 0,
                  "restored forward after rollback boundary");
            for (int v = 0; v < cfg.vocab; v++)
                CHECK(expected_logits[v] == rollback_logits[v],
                      "post-rollback logits stay bit-exact across ring wrap");
        }
    }
    dsv4_context_snapshot_free(snap);
    dsv4_model_close(rollback_m);
    dsv4_model_close(expected_m);
    free(rollback_logits);
    free(expected_logits);

    /* A verified prefix can be committed without replaying the main model.
     * The rejected suffix has already overwritten ring slots and compressor
     * state, so this exercises selective row restore plus per-position state. */
    DSV4Model *commit_expected_m = dsv4_model_open(fdir, &opt);
    DSV4Model *commit_m = dsv4_model_open(fdir, &opt);
    float *commit_expected_logits =
        (float *)malloc((size_t)cfg.vocab * sizeof(float));
    float *commit_logits = (float *)malloc((size_t)cfg.vocab * sizeof(float));
    DSV4ContextSnapshot *commit_snap =
        dsv4_context_snapshot_create(commit_m, 6);
    CHECK(commit_expected_m != NULL, "prefix-commit reference model open");
    CHECK(commit_m != NULL, "prefix-commit model open");
    CHECK(commit_expected_logits != NULL && commit_logits != NULL,
          "prefix-commit logits allocations");
    CHECK(commit_snap != NULL, "prefix-commit snapshot allocation");
    if (commit_expected_m && commit_m && commit_expected_logits &&
        commit_logits && commit_snap) {
        CHECK(dsv4_prefill(commit_expected_m, rollback_ids, 126, 0,
                           commit_expected_logits) == 0,
              "prefix-commit reference prefix");
        CHECK(dsv4_prefill(commit_m, rollback_ids, 126, 0, commit_logits) == 0,
              "prefix-commit test prefix");
        CHECK(dsv4_context_snapshot_take(commit_snap, 126, 6) == 0,
              "take prefix-commit snapshot");
        CHECK(dsv4_prefill(commit_m, wrong_ids, 6, 126, commit_logits) == 0,
              "verify block before direct prefix commit");
        CHECK(dsv4_context_snapshot_commit_prefix(commit_snap, 2) == 0,
              "commit verified prefix without replay");
        CHECK(dsv4_prefill(commit_expected_m, rollback_ids + 126, 2, 126,
                           commit_expected_logits) == 0,
              "prefix-commit reference accepted rows");
        CHECK(same_context(commit_expected_m, commit_m),
              "direct prefix commit restores every rejected-suffix state byte");
        for (int pos = 128; pos < 132; pos++) {
            CHECK(dsv4_forward_token(commit_expected_m, rollback_ids[pos], pos,
                                     commit_expected_logits) == 0,
                  "prefix-commit reference continuation");
            CHECK(dsv4_forward_token(commit_m, rollback_ids[pos], pos,
                                     commit_logits) == 0,
                  "direct prefix-commit continuation");
            for (int v = 0; v < cfg.vocab; v++)
                CHECK(commit_expected_logits[v] == commit_logits[v],
                      "direct prefix-commit logits remain bit-exact");
        }
    }
    dsv4_context_snapshot_free(commit_snap);
    dsv4_model_close(commit_m);
    dsv4_model_close(commit_expected_m);
    free(commit_logits);
    free(commit_expected_logits);

    /* A resident chat appends later turns to an existing KV/compressor state.
     * Splitting the same sequence at an arbitrary turn boundary must reproduce
     * one layer-major prefill exactly. */
    DSV4Model *split_m = dsv4_model_open(fdir, &opt);
    float *split_logits = (float *)malloc((size_t)cfg.vocab * sizeof(float));
    CHECK(split_m != NULL, "split-prefill model open");
    CHECK(split_logits != NULL, "split-prefill logits allocation");
    if (split_m && split_logits) {
        CHECK(dsv4_prefill(split_m, batch_ids, 57, 0, split_logits) == 0,
              "first resident prefill segment");
        CHECK(dsv4_prefill(split_m, batch_ids + 57, 73, 57, split_logits) == 0,
              "second resident prefill segment");
        for (int v = 0; v < cfg.vocab; v++)
            CHECK(split_logits[v] == logits[v],
                  "split resident prefill matches one-shot path");
        CHECK(split_m->forward_steps == 130, "split forward-step accounting");
    }
    dsv4_model_close(split_m);
    free(split_logits);

    /* Prompt-lookup verification temporarily gives hash-routed layers more
     * slots, then restores the scalar-decode partition. The tiny fixture has
     * no hash layer, so mark layer zero as the partition owner only inside
     * this cache-scheduling test; graph weights and numerical work are
     * unchanged. Twelve slots leave room to resize 2 -> 6 -> 2 after the
     * first prefill segment has populated the cache. */
    DSV4Options rebalance_opt = opt;
    rebalance_opt.expert_cache_bytes =
        12u * (13369344ull + 4 * 4096ull);
    DSV4Model *rebalance_m = dsv4_model_open(fdir, &rebalance_opt);
    float *rebalance_logits =
        (float *)malloc((size_t)cfg.vocab * sizeof(float));
    CHECK(rebalance_m != NULL, "cache-rebalance model open");
    CHECK(rebalance_logits != NULL, "cache-rebalance logits allocation");
    if (rebalance_m && rebalance_logits) {
        rebalance_m->cfg.n_hash_layers = 1;
        rebalance_m->cfg.n_experts = 6;
        rebalance_m->cache_hash_min = 1;
        rebalance_m->cache_hash_slots = cfg.topk;
        CHECK(rebalance_m->cache_per_layer && rebalance_m->cache_slru,
              "cache-rebalance uses per-layer SLRU");
        rebalance_m->cfg.n_hash_layers = 0;
        rebalance_m->cfg.n_experts = cfg.n_experts;
        rebalance_m->cache_hash_min = 0;
        CHECK(dsv4_prefill(rebalance_m, batch_ids, 57, 0,
                           rebalance_logits) == 0,
               "cache-rebalance first prefill segment");
        rebalance_m->cfg.n_hash_layers = 1;
        rebalance_m->cfg.n_experts = 6;
        rebalance_m->cache_hash_min = 1;
        rebalance_m->cache_hash_slots = cfg.topk;
        CHECK(dsv4_expert_cache_set_hash_slots(rebalance_m, 6) == 0,
              "expand populated hash cache partition");
        CHECK(rebalance_m->cache_hash_slots == 6,
              "expanded hash cache owns six slots");
        CHECK(dsv4_expert_cache_set_hash_slots(rebalance_m, cfg.topk) == 0,
              "round-trip populated hash cache partition");
        rebalance_m->cfg.n_hash_layers = 0;
        rebalance_m->cfg.n_experts = cfg.n_experts;
        rebalance_m->cache_hash_min = 0;
        CHECK(dsv4_prefill(rebalance_m, batch_ids + 57, 73, 57,
                           rebalance_logits) == 0,
              "cache-rebalance second prefill segment");
        rebalance_m->cfg.n_hash_layers = 1;
        rebalance_m->cfg.n_experts = 6;
        rebalance_m->cache_hash_min = 1;
        rebalance_m->cache_hash_slots = cfg.topk;
        CHECK(dsv4_expert_cache_set_hash_slots(rebalance_m, cfg.topk) == 0,
              "restore scalar hash cache partition");
        CHECK(rebalance_m->cache_hash_slots == cfg.topk,
              "restored hash cache owns top-k slots");
        rebalance_m->cfg.n_hash_layers = 0;
        rebalance_m->cfg.n_experts = cfg.n_experts;
        rebalance_m->cache_hash_min = 0;
        for (int v = 0; v < cfg.vocab; v++)
            CHECK(rebalance_logits[v] == logits[v],
                  "cache resize round trip preserves final logits");
    }
    dsv4_model_close(rebalance_m);
    free(rebalance_logits);

    /* The scheduling-only optimisation must also agree with its synchronous
     * fallback in the same binary. */
    CHECK(setenv("DSV4_NO_EXPERT_OVERLAP", "1", 1) == 0,
          "disable expert overlap for A/B test");
    DSV4Model *sync_m = dsv4_model_open(fdir, &opt);
    float *sync_logits = (float *)malloc((size_t)cfg.vocab * sizeof(float));
    CHECK(sync_m != NULL, "synchronous model open");
    CHECK(sync_logits != NULL, "synchronous logits allocation");
    if (sync_m && sync_logits) {
        CHECK(dsv4_prefill(sync_m, batch_ids, 130, 0, sync_logits) == 0,
              "synchronous layer-major prefill");
        for (int v = 0; v < cfg.vocab; v++)
            CHECK(sync_logits[v] == logits[v],
                  "overlapped and synchronous logits match");
    }
    dsv4_model_close(sync_m);
    free(sync_logits);
    CHECK(unsetenv("DSV4_NO_EXPERT_OVERLAP") == 0,
          "restore expert overlap after A/B test");

    /* A chat reset clears every position-dependent state while retaining the
     * expensive model and weight caches. Replaying from position zero must be
     * bit-exact with the independent scalar oracle. */
    dsv4_model_reset_context(m);
    for (int pos = 0; pos < 16; pos++) {
        CHECK(dsv4_forward_token(m, seq[pos], pos, logits) == 0,
              "forward after context reset");
        char key[16];
        snprintf(key, sizeof key, "%d", pos);
        for (int v = 0; v < cfg.vocab; v++)
            CHECK((double)logits[v] == ref_at(ref, key, v),
                  "context reset replay matches scalar oracle");
    }
    free(logits);

    dsv4_model_close(m);
    free(txt);
    json_free(ref);
    if (fails) { printf("%d FAILURES\n", fails); return 1; }
    printf("maxdiff=%.6f at pos=%d v=%d\n", maxdiff, maxpos, maxv);
    printf("test_dsv4_model: PASS (130 positions, ratios 4/128 boundaries crossed)\n");
    return 0;
}
